openapi: 3.1.0
info:
  title: Task CRUD API
  description: Phase 2 Part 3 - Task management endpoints with authentication
  version: 1.0.0
  contact:
    name: Todo Evolution Project

servers:
  - url: http://localhost:8000
    description: Local development server

security:
  - bearerAuth: []

paths:
  /tasks:
    get:
      summary: List tasks
      description: |
        Returns a paginated list of tasks owned by the authenticated user.
        Supports filtering by status and date, sorting, and pagination.
      operationId: listTasks
      tags:
        - Tasks
      parameters:
        - name: status
          in: query
          description: Filter by task status
          schema:
            $ref: '#/components/schemas/TaskStatus'
        - name: created_after
          in: query
          description: Filter tasks created after this date (ISO format)
          schema:
            type: string
            format: date
            example: "2025-01-01"
        - name: created_before
          in: query
          description: Filter tasks created before this date (ISO format)
          schema:
            type: string
            format: date
            example: "2025-12-31"
        - name: sort
          in: query
          description: "Sort field and direction (format: field:direction)"
          schema:
            type: string
            default: "created_at:desc"
            enum:
              - created_at:asc
              - created_at:desc
              - updated_at:asc
              - updated_at:desc
              - title:asc
              - title:desc
              - status:asc
              - status:desc
        - name: limit
          in: query
          description: Number of items per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of items to skip
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Paginated list of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTaskResponse'
              example:
                items:
                  - id: "550e8400-e29b-41d4-a716-446655440000"
                    title: "Complete project"
                    description: "Finish the API implementation"
                    status: "pending"
                    created_at: "2025-12-14T10:00:00Z"
                    updated_at: "2025-12-14T10:00:00Z"
                total: 1
                limit: 20
                offset: 0
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/ValidationError'

    post:
      summary: Create task
      description: Create a new task for the authenticated user
      operationId: createTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
            example:
              title: "New task"
              description: "Task description"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskRead'
              example:
                id: "550e8400-e29b-41d4-a716-446655440001"
                title: "New task"
                description: "Task description"
                status: "pending"
                created_at: "2025-12-14T10:30:00Z"
                updated_at: "2025-12-14T10:30:00Z"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/RateLimited'

  /tasks/{task_id}:
    parameters:
      - name: task_id
        in: path
        required: true
        description: Task UUID
        schema:
          type: string
          format: uuid

    get:
      summary: Get task
      description: |
        Get a specific task by ID. Returns 404 if task doesn't exist
        or is not owned by the authenticated user.
      operationId: getTask
      tags:
        - Tasks
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskRead'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    patch:
      summary: Update task
      description: |
        Partially update a task. Only provided fields are updated.
        Returns 404 if task doesn't exist or is not owned by the authenticated user.
      operationId: updateTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
            example:
              status: "completed"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskRead'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/RateLimited'

    delete:
      summary: Delete task
      description: |
        Delete a task. Returns 404 if task doesn't exist
        or is not owned by the authenticated user.
      operationId: deleteTask
      tags:
        - Tasks
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/RateLimited'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token obtained from /auth/login

  schemas:
    TaskStatus:
      type: string
      enum:
        - pending
        - completed
      description: Task completion status

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title (required)
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          nullable: true
          description: Optional task description
          example: "Milk, eggs, bread"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Updated task title
        description:
          type: string
          maxLength: 1000
          nullable: true
          description: Updated task description
        status:
          $ref: '#/components/schemas/TaskStatus'

    TaskRead:
      type: object
      required:
        - id
        - title
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
        title:
          type: string
          description: Task title
        description:
          type: string
          nullable: true
          description: Task description
        status:
          $ref: '#/components/schemas/TaskStatus'
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
      # Note: user_id intentionally excluded for security

    PaginatedTaskResponse:
      type: object
      required:
        - items
        - total
        - limit
        - offset
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TaskRead'
          description: List of tasks
        total:
          type: integer
          minimum: 0
          description: Total count of matching tasks
        limit:
          type: integer
          description: Page size
        offset:
          type: integer
          description: Current offset

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message

    ValidationErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: integer
                description: Error location path
              msg:
                type: string
                description: Error message
              type:
                type: string
                description: Error type

  responses:
    Unauthorized:
      description: Not authenticated or invalid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Not authenticated"

    NotFound:
      description: Task not found or not owned by user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Task not found"

    BadRequest:
      description: Invalid request data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Invalid sort format"

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationErrorResponse'
          example:
            detail:
              - loc: ["body", "title"]
                msg: "String should have at least 1 character"
                type: "string_too_short"

    RateLimited:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Rate limit exceeded. Try again in 1800 seconds."

tags:
  - name: Tasks
    description: Task CRUD operations with user ownership
