apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: todo-app
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: todo-backend:updated
        command: ["python", "-c", "import asyncio; from app.core.database import get_async_engine, init_db; async def main(): engine = get_async_engine(); await init_db(); print('Database initialized successfully'); asyncio.run(main())"]
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://postgres:postgres@postgresql:5432/todo_db"
        - name: JWT_SECRET_KEY
          value: "my-super-secret-jwt-key-for-demo"
      restartPolicy: Never
  backoffLimit: 4