# Dapr Secrets Store Component
# This component securely manages API keys, credentials, and sensitive configuration
# Usage: Store OpenAI API keys, database credentials, Kafka credentials

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: taskgpt
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []

---
# For local development, use local secret store
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secrets
  namespace: taskgpt
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "/mnt/secrets/secrets.json"
    - name: nestedSeparator
      value: ":"

---
# Example Kubernetes Secret for PostgreSQL
# Create this secret with:
# kubectl create secret generic postgres-secrets \
#   --from-literal=connectionString="host=... user=... password=... dbname=... sslmode=require"

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: taskgpt
type: Opaque
stringData:
  connectionString: "host=YOUR_NEON_HOST user=YOUR_USER password=YOUR_PASSWORD dbname=todo port=5432 sslmode=require"

---
# Example Kubernetes Secret for Kafka/Redpanda Cloud
# Create this secret with:
# kubectl create secret generic kafka-secrets \
#   --from-literal=username="YOUR_USERNAME" \
#   --from-literal=password="YOUR_PASSWORD"

apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: taskgpt
type: Opaque
stringData:
  username: "YOUR_KAFKA_USERNAME"
  password: "YOUR_KAFKA_PASSWORD"
  brokers: "YOUR_CLUSTER.cloud.redpanda.com:9092"

---
# Example Kubernetes Secret for OpenAI
# Create this secret with:
# kubectl create secret generic openai-secrets \
#   --from-literal=api-key="sk-..."

apiVersion: v1
kind: Secret
metadata:
  name: openai-secrets
  namespace: taskgpt
type: Opaque
stringData:
  api-key: "YOUR_OPENAI_API_KEY"

---
# Example local secrets file format (secrets.json):
# {
#   "postgres": {
#     "connectionString": "host=... user=... password=..."
#   },
#   "kafka": {
#     "username": "...",
#     "password": "...",
#     "brokers": "..."
#   },
#   "openai": {
#     "api-key": "sk-..."
#   }
# }
#
# Access in code:
# - PostgreSQL: postgres:connectionString
# - Kafka username: kafka:username
# - OpenAI API key: openai:api-key
